name: basic-schulung
on: 
    push:
    workflow_dispatch:
    
jobs:
 build: 
   name: first_action
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: ./action-a
       with: 
         MY_NAME: simon
